export const GET_INFORMATION_SUCCEEDED = 'GET_INFORMATION_SUCCEEDED'
export const GET_INFORMATION_FAILED = 'GET_INFORMATION_FAILED'

export const GET_INFORMATION_DETAIL_SUCCEEDED = 'GET_INFORMATION_DETAIL_SUCCEEDED'
export const GET_INFORMATION_DETAIL_FAILED = 'GET_INFORMATION_DETAIL_FAILED'