export const GET_ALL_SIGN_SUCCEEDED = 'GET_ALL_SIGN_SUCCEEDED'
export const GET_ALL_SIGN_FAILED = 'GET_ALL_SIGN_FAILED'

export const GET_SIGN_RECORD_DETAIL_SUCCEEDED = 'GET_SIGN_RECORD_DETAIL_SUCCEEDED'
export const GET_SIGN_RECORD_DETAIL_FAILED = 'GET_SIGN_RECORD_DETAIL_FAILED'
