export const GET_NEWS_LIST_SUCCEEDED = 'GET_NEWS_LIST_SUCCEEDED'
export const GET_NEWS_LIST_FAILED = 'GET_NEWS_LIST_FAILED'

export const GET_NEWS_DETAIL_SUCCEEDED = 'GET_NEWS_DETAIL_SUCCEEDED'
export const GET_NEWS_DETAIL_FAILED = 'GET_NEWS_DETAIL_FAILED'

export const GET_NEWS_COMMENTS_SUCCEEDED = 'GET_NEWS_COMMENTS_SUCCEEDED'
export const GET_NEWS_COMMENTS_FAILED = 'GET_NEWS_COMMENTS_FAILED'

export const ADD_NEWS_COMMENTS_SUCCEEDED = 'ADD_NEWS_COMMENTS_SUCCEEDED'
export const ADD_NEWS_COMMENTS_FAILED = 'ADD_NEWS_COMMENTS_FAILED'