export const GET_NEWS_LIST_SUCCEEDED = 'GET_NEWS_LIST_SUCCEEDED'
export const GET_NEWS_LIST_FAILED = 'GET_NEWS_LIST_FAILED'

export const GET_NEWS_DETAIL_SUCCEEDED = 'GET_NEWS_DETAIL_SUCCEEDED'
export const GET_NEWS_DETAIL_FAILED = 'GET_NEWS_DETAIL_FAILED'