export const TEST = 'TEST'
// 获取绑定，成员信息
export const GET_USER_INFO_SUCCEEDED = 'GET_USER_INFO_SUCCEEDED'
export const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED'
// 绑定
export const BOUND_USER_INFO_SUCCEEDED = 'BOUND_USER_INFO_SUCCEEDED'
export const BOUND_USER_INFO_FAILED = 'BOUND_USER_INFO_FAILED'

